# Рабочая тетрадь 2
## 1.3.1

In [10]:
import numpy as np
a = np.zeros((8,8))
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


## 1.3.2

In [14]:
q = np.zeros((5, 5))
q[:,:] = np.arange(0, 5)
print(q)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


## 1.3.3

In [20]:
a = np.random.random((3, 3, 3))
print(a)

[[[0.24740545 0.89791617 0.66183434]
  [0.78351113 0.53700074 0.23758967]
  [0.86925226 0.0697907  0.04666509]]

 [[0.30524847 0.05043586 0.19613883]
  [0.48318036 0.53260008 0.22056067]
  [0.99696884 0.08217338 0.87739544]]

 [[0.82338329 0.62052279 0.28486648]
  [0.75761641 0.25335338 0.17257692]
  [0.6063491  0.0281634  0.2959328 ]]]


## 1.3.4

In [46]:
a = np.ones((5,5))
a[1:4, 1:4] = 0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## 1.3.5

In [56]:
a = np.random.random(5)
a = sorted(a)[::-1]
print(a)

[0.9303766968026358, 0.7685323730119406, 0.23038645032536476, 0.08678433459888613, 0.06266990045596943]


## 1.3.6

In [62]:
a = np.array([[1, 3, 6], [1, 5, 3], [1 ,3, 2], [1, 5, 5]])
print(a.shape, a.ndim, sep=', ')

(4, 3), 2


## 2.3.1

In [81]:
import pandas as pd
from math import sqrt
a = pd.Series([5, 5, 4])
b = pd.Series([1, 3, 8])
print(sqrt(sum((b - a)**2)))

6.0


## 2.3.2 - 2.3.3

In [105]:
url = 'https://raw.githubusercontent.com/akmand/datasets/master/baby_names_2000.csv'
df = pd.read_csv(url)

In [106]:
df.head()

year     name gender  count
0  2000    Emily      F  25956
1  2000   Hannah      F  23082
2  2000  Madison      F  19968
3  2000   Ashley      F  17997
4  2000    Sarah      F  17702

In [107]:
df.tail()

year   name gender  count
624231  2018  Zylas      M      5
624232  2018  Zyran      M      5
624233  2018  Zyrie      M      5
624234  2018  Zyron      M      5
624235  2018  Zzyzx      M      5

In [108]:
df.shape

(624236, 4)

In [109]:
df.describe()

year          count
count  624236.000000  624236.000000
mean     2009.115961     113.971929
std         5.383550     754.696900
min      2000.000000       5.000000
25%      2005.000000       7.000000
50%      2009.000000      11.000000
75%      2014.000000      29.000000
max      2018.000000   34477.000000

In [112]:
df.iloc[1:10,[1, 2]]

name gender
1     Hannah      F
2    Madison      F
3     Ashley      F
4      Sarah      F
5     Alexis      F
6   Samantha      F
7    Jessica      F
8  Elizabeth      F
9     Taylor      F

In [114]:
df[df['name'] == 'Tyler'].head()

year   name gender  count
415    2000  Tyler      F    683
17664  2000  Tyler      M  21504
30262  2001  Tyler      F    569
47757  2001  Tyler      M  19273
60570  2002  Tyler      F    523

## 3.3.2

In [163]:
import numpy as np
import pandas as pd
from sklearn import preprocessing

url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
df = pd.read_csv(url)

# minimax
feature1 = np.array([df['sepal_length_cm']]).reshape(-1, 1)

minimax_scale = preprocessing.MinMaxScaler(feature_range = (0, 1))
scaled_feature = minimax_scale.fit_transform(feature1)
scaled_feature

array([[0.22222222],
       [0.16666667],
       [0.11111111],
       [0.08333333],
       [0.19444444],
       [0.30555556],
       [0.08333333],
       [0.19444444],
       [0.02777778],
       [0.16666667],
       [0.30555556],
       [0.13888889],
       [0.13888889],
       [0.        ],
       [0.41666667],
       [0.38888889],
       [0.30555556],
       [0.22222222],
       [0.38888889],
       [0.22222222],
       [0.30555556],
       [0.22222222],
       [0.08333333],
       [0.22222222],
       [0.13888889],
       [0.19444444],
       [0.19444444],
       [0.25      ],
       [0.25      ],
       [0.11111111],
       [0.13888889],
       [0.30555556],
       [0.25      ],
       [0.33333333],
       [0.16666667],
       [0.19444444],
       [0.33333333],
       [0.16666667],
       [0.02777778],
       [0.22222222],
       [0.19444444],
       [0.05555556],
       [0.02777778],
       [0.19444444],
       [0.22222222],
       [0.13888889],
       [0.22222222],
       [0.083

In [167]:
# stdscaler
feature2 = np.array([df['sepal_width_cm']]).reshape(-1, 1)
scaler_z = preprocessing.StandardScaler()
standarized = scaler_z.fit_transform(feature2)
standarized

array([[ 1.03205722],
       [-0.1249576 ],
       [ 0.33784833],
       [ 0.10644536],
       [ 1.26346019],
       [ 1.95766909],
       [ 0.80065426],
       [ 0.80065426],
       [-0.35636057],
       [ 0.10644536],
       [ 1.49486315],
       [ 0.80065426],
       [-0.1249576 ],
       [-0.1249576 ],
       [ 2.18907205],
       [ 3.11468391],
       [ 1.95766909],
       [ 1.03205722],
       [ 1.72626612],
       [ 1.72626612],
       [ 0.80065426],
       [ 1.49486315],
       [ 1.26346019],
       [ 0.56925129],
       [ 0.80065426],
       [-0.1249576 ],
       [ 0.80065426],
       [ 1.03205722],
       [ 0.80065426],
       [ 0.33784833],
       [ 0.10644536],
       [ 0.80065426],
       [ 2.42047502],
       [ 2.65187798],
       [ 0.10644536],
       [ 0.33784833],
       [ 1.03205722],
       [ 0.10644536],
       [-0.1249576 ],
       [ 0.80065426],
       [ 1.03205722],
       [-1.74477836],
       [ 0.33784833],
       [ 1.03205722],
       [ 1.72626612],
       [-0

In [117]:
# Необходимо выполнить нормализацию первого числового признака
# (sepal_length_cm) с использованием минимаксного преобразования, а
# второго (sepal_width_cm) с задействованием z-масштабирования